# # # # # # # # # # # # #
#   K i k o - p l u s   #
# # # # # # # # # # # # #

# Basic
name:               "twopointseven"

author:
  twitter:          
  email:            tejpalv8@gmail.com,jtgg01@gmail.com

copyright:
  year:             2017
  name:             twopointseven

# Google-analytics
google-analytics:
  id:               ""

# Disqus
disqus:
  id:               "twopointseven"

# URL
url:                "https://tvirdi.github.io" # the base hostname & protocol for your site
# url:                "http://localhost:4000" # use this url when you develop
#baseurl:            "/Kiko-plus" # the subpath of your site, e.g. /blog

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           US/Pacific
permalink:          /:year-:month-:day/:title/

# Pagination
paginate:           30
paginate_path:      /page:num/

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
   input: GFM
   hard_wrap: false
   # syntax_highlighter: rouge

# Navigation
nav:
  - name:           "about"
    url:            "/about"


# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
gems:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-admin

exclude:            [vendor]
github:             [metadata]